# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-aarch64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-aarch64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/ca-certificates-2024.7.2-hd43f75c_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/ld_impl_linux-aarch64-2.38-h8131f2d_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2024a-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/_openmp_mutex-5.1-51_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/bzip2-1.0.8-h998d150_6.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/libffi-3.4.4-h419075a_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/libuuid-1.41.5-h998d150_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/ncurses-6.4-h419075a_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/openssl-3.0.15-h998d150_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/xz-5.4.6-h998d150_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/zlib-1.2.13-h998d150_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/readline-8.2-h998d150_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/tk-8.6.14-h987d8db_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/sqlite-3.45.3-h998d150_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/python-3.10.14-h4bb2201_1.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/setuptools-72.1.0-py310hd43f75c_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/wheel-0.44.0-py310hd43f75c_0.conda
https://repo.anaconda.com/pkgs/main/linux-aarch64/pip-24.2-py310hd43f75c_0.conda
